version: 2.1
executors:
  app-init:
    docker:
      - image: cimg/node:20.17.0
      - image: cimg/redis:7.2.5
      - image: 'cibuilds/base:latest'
    working_directory: ~/repo
  terraform-init:
    docker:
      - image: hashicorp/terraform:latest
  slack-init:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}
  - &zip-project
    run:
      name: Zip project
      command: |
          rm -rf node_modules
          zip gxitr.zip -r .
          echo "Zip successful"
