@baseUrl = http://localhost:8008
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "a-star",
  "email": "esther@kaycee.co",
  "password": "kira22bo",
  "avatarColor": "peach",
  "roles": ["org:admin", "org:user"],
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0gAAAMyAQMAAABtkHM/AAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAAFiS0dEAf8Cld4AAABrSURBVBgZ7cGBAAAAAMOg+1NP4AjVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgBSwwABwrL8wAAAAABJRU5ErkJggg=="
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "login": "a-star",
  "password": "kira22bo"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "esther@kaycee.co"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/<token>
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "a_star22kira",
  "confirmPassword": "a_star22kira"
}
