@baseUrl = http://localhost:8008
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "praise",
  "email": "chi.pra@kaycee.co",
  "password": "kara18chi",
  "avatarColor": "blue",
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0gAAAMyAQMAAABtkHM/AAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAAFiS0dEAf8Cld4AAABrSURBVBgZ7cGBAAAAAMOg+1NP4AjVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgBSwwABwrL8wAAAAABJRU5ErkJggg=="
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "login": "a_star",
  "password": "kira22bo"
}
