@baseUrl = http://localhost:8008
@urlPath = api/v1

@userId =

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "",
  "receiverId": "",
  "receiverUsername": "",
  "receiverAvatarColor": "",
  "receiverProfilePicture": "",
  "body": "Hello.. howdy?",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/users/add
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "",
  "userTwo": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/users/remove
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "",
  "userTwo": ""
}

###
GET {{baseUrl}}/{{urlPath}}/chat/conversations
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
GET {{baseUrl}}/{{urlPath}}/chat/conversations/{{userId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }
