@baseUrl = http://localhost:8008
@urlPath = api/v1
@followeeId = 66914a50b5b3537535533054
@userId = 66914a50b5b3537535533054

###
PUT {{baseUrl}}/{{urlPath}}/follow/{{followeeId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
PUT {{baseUrl}}/{{urlPath}}/unfollow/{{followeeId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
GET {{baseUrl}}/{{urlPath}}/followers/{{userId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
GET {{baseUrl}}/{{urlPath}}/following/{{userId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
GET {{baseUrl}}/{{urlPath}}/followers
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
GET {{baseUrl}}/{{urlPath}}/following
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }
