@baseUrl = http://localhost:8008
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "This is my first sample post",
  "bgColor": "#4aa1f3",
  "scope": "Public",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dahrlgvpt/image/upload/v1719781047/6681c6a275b313a186073ee3",
  "feelings": "happy"
}
