@baseUrl = http://localhost:8008
@urlPath = api/v1
@notificationId =
@userId =

###
GET {{baseUrl}}/{{urlPath}}/notifications/{{userId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
PUT {{baseUrl}}/{{urlPath}}/notification/{{notificationId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }

###
DELETE  {{baseUrl}}/{{urlPath}}/notification/{{notificationId}}
Content-Type: application/json
Accept: application/json
withCredentials: true

{ }
